# Generated by Django 3.1.5 on 2021-01-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210129_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='posttype',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='posttype',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
