# Generated by Django 3.1.5 on 2021-01-31 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_askquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='major_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='university_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.major'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.university'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='academic_year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cover_photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nrc_passport',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='studentID',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_role',
            field=models.IntegerField(default=0),
        ),
    ]
