# Generated by Django 3.1.5 on 2021-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210131_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_role',
            field=models.IntegerField(default='0'),
        ),
    ]
