# Generated by Django 3.1.5 on 2021-03-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210131_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_role',
            field=models.IntegerField(default=0),
        ),
    ]
