# Generated by Django 3.1.5 on 2021-03-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210325_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='university_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
