# Generated by Django 3.1.7 on 2021-04-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210403_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cover_photo',
            field=models.TextField(null=True),
        ),
    ]
