# Generated by Django 3.1.7 on 2021-04-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210403_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='city_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='country_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='cover_photo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='google_map_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='major_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='profile_picture',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='representative_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
