# Generated by Django 3.1.7 on 2021-04-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210406_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='admin_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
