# Generated by Django 3.1.7 on 2021-04-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210406_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='cover_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
