# Generated by Django 3.1.7 on 2021-04-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210408_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='representative_id',
        ),
    ]
