# Generated by Django 3.1.5 on 2021-01-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_id', models.IntegerField()),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('post_type_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('university_id', models.IntegerField()),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('city_id', models.IntegerField()),
                ('country_id', models.IntegerField()),
                ('profile_picture', models.CharField(max_length=255)),
                ('cover_photo', models.CharField(max_length=255)),
                ('representative_id', models.IntegerField()),
                ('description', models.TextField()),
                ('major_id', models.IntegerField()),
                ('google_map_link', models.TextField()),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nrc_passport', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('studentID', models.CharField(max_length=20)),
                ('university_id', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('city_id', models.IntegerField()),
                ('country_id', models.IntegerField()),
                ('major_id', models.IntegerField()),
                ('academic_year', models.CharField(max_length=10)),
                ('profile_picture', models.CharField(max_length=255)),
                ('cover_photo', models.CharField(max_length=255)),
                ('user_role', models.IntegerField()),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
