# Generated by Django 3.1.5 on 2021-01-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210129_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
    ]
